services:
  app:
    image: php:8.2-fpm
    container_name: botones_laravel_app
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: botones_laravel_nginx
    ports:
      - "8081:80"  # El puerto 80 del contenedor se mapea al puerto 8081 del host
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: botones_laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
